version: '3.4'

services:
  redis-master:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=redis
    ports:
      - '6379:6379'
    network_mode: "host"
  redis-slave:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_PORT_NUMBER=6380
      - REDIS_REPLICA_IP=127.0.0.1
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=127.0.0.1
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=redis
      - REDIS_REPLICA_PORT=6380
    ports:
      - '6380:6380'
    network_mode: "host"
    depends_on:
      - redis-master
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_SENTINEL_PASSWORD=redis
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=redis
      - REDIS_SENTINEL_QUORUM=2
      - REDIS_SENTINEL_MASTER_REBOOT_DOWN_AFTER_PERIOD=10000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=1000
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=10000
      - REDIS_MASTER_HOST=127.0.0.1
    network_mode: "host"
    ports:
      - '26379:26379'
    depends_on:
      - redis-master
      - redis-slave
  redis-sentinel-2:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_SENTINEL_PASSWORD=redis
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=redis
      - REDIS_SENTINEL_PORT_NUMBER=26380
      - REDIS_SENTINEL_ANNOUNCE_PORT=26380
      - REDIS_SENTINEL_QUORUM=2
      - REDIS_SENTINEL_MASTER_REBOOT_DOWN_AFTER_PERIOD=10000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=1000
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=10000
      - REDIS_MASTER_HOST=127.0.0.1
    network_mode: "host"
    ports:
      - '26380:26380'
    depends_on:
      - redis-master
      - redis-slave