include:
    - docker-compose-redis.yml
    - docker-compose-db.yml

name: gauniv
services:
    gauniv.webserver:
        image: ${DOCKER_REGISTRY-}gaunivwebserver
        build:
            context: .
            dockerfile: Gauniv.WebServer/Dockerfile
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_HTTP_PORTS=80
          - ASPNETCORE_HTTPS_PORTS=443
          - ConnectionStrings:DefaultConnection=Server=postgres_primary;Port=5432;Database=db;Username=admin;Password=password
          - ConnectionStrings:redis=redis-sentinel:26379,serviceName=mymaster,password=redis
        ports:
          - "80"
          - "443"
        volumes:
          - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
          - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./certificate:/certificate:ro
        depends_on:
            - gauniv.webserver
        ports:
            - "80:80"
            - "443:443"
            - "15000:15000"

