name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.100-rc.2.24474.11'  # This is the correct RC version number
    
    - name: Restore dependencies
      run: dotnet restore Gauniv.sln
      
    - name: Build
      run: dotnet build Gauniv.sln --no-restore --configuration Release